services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: vet_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - vet-network

  app:
    build: .
    container_name: vet_backend_app
    ports:
      - "${SERVER_PORT:-8080}:8080"
    depends_on:
      - db
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      SERVER_PORT: 8080
    networks:
      - vet-network

volumes:
  pgdata:

networks:
  vet-network:
    name: vet-network
    driver: bridge